alias ll="ls -alF --color=auto"
alias la="ls -A"
alias l="ls -CF"
alias cls="clear"
alias ..="cd .."
alias ...="cd ../.."
alias matrix="cmatrix -b -C green"
alias reload="source ~/.bashrc"
alias yr1="cd ~/Developer/LiU_year1"
